site_name: Spike + Loop Wiki
nav:
- Home: 'index.md'
- FAQ: 'faq.md'
- Calibration: 'calibration.md'
- The Spike Branches: 'about.md'
- Troubleshooting: 'troubleshooting.md'
markdown_extensions:
  - admonition
theme: cinder
extra_javascript:
  - 'js/refreshUpdatesRepo.js'
